version: '3.3'

services:
  template_vue:
    image: template_vue
    ports:
      - 80:3000
    command: "yarn serve"
    environment:
      - CHOKIDAR_USEPOLLING=true
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./:/home/app
      - /home/app/node_modules
